In [36]:
import torch
from torch import nn
from torch.nn import functional as F
import matplotlib.pyplot as plt

In [37]:
class MLP(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.hidden=nn.Linear(4,256)
        self.out=nn.Linear(256,10)
    def forward(self,X):
        return self.out(F.relu(self.hidden(X)))

In [38]:
X=torch.tensor([[1,2.,2,3],[23,2,6,5]])
def block1():
    return nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,4))
def block2():
    net=nn.Sequential()
    for i in range (4):
        net.add_module(f'block {i}', block1())
    return net

net=nn.Sequential(block1(),nn.Linear(4,1))
net(X)

tensor([[0.5324],
        [1.9845]], grad_fn=<AddmmBackward0>)

In [39]:
def init_normal(m):
    if type(m)==nn.Linear:
        nn.init.normal_(m.weight,mean=0,std=0.01)
        nn.init.zeros_(m.bias)

net.apply(init_normal)




Sequential(
  (0): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)

In [40]:
class meanlayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

In [41]:
layer=meanlayer()
layer(torch.tensor([1.,2]))

tensor([-0.5000,  0.5000])

In [42]:
class Mylinear(nn.Module):
    def __init__(self,in_unit,units) -> None:
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_unit,units))
        self.bias=nn.Parameter(torch.zeros(units,))
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return linear
dense=Mylinear(5,3)
dense(torch.rand(2,5))

tensor([[ 1.9742, -0.1091, -0.1652],
        [ 1.7946, -0.7841, -0.7631]])

In [43]:
x=torch.arange(4)
torch.save(x,'xfile')
y=torch.load('xfile')

In [44]:
mlpnet=MLP()
torch.save(mlpnet.state_dict(),'mlp.params')
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()
clone(X)

MLP(
  (hidden): Linear(in_features=4, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)