In [1]:
import torch


In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel

<function Tensor.numel>

In [5]:
x=x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
a=x.numpy()

In [9]:
torch.tensor([1,2.2])

tensor([1.0000, 2.2000])

In [74]:
import os
data_file=os.path.join('house.csv')
with open(data_file,'w') as f:
    f.write('numrooms,apple\n')
    f.write('1,a\n')
    f.write('2,b\n')


import pandas as pd
data=pd.read_csv(data_file)

inputs=pd.get_dummies(data,dummy_na=True)
X=torch.tensor(inputs.values)
X,X.sum(axis=1,keepdims=True)
# torch.norm(X)







(tensor([[1, 1, 0, 0],
         [2, 0, 1, 0]]),
 tensor([[2],
         [3]]))

In [90]:
x=torch.arange(4.0)
x.requires_grad_(True)
y=2*torch.dot(x,x)
y.backward()
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y=x*x
